export type Locale = 'pt' | 'en';
export const LOCALES: Locale[] = ['pt', 'en'];
export const DEFAULT_LOCALE: Locale = 'pt';

export const AUTHOR = {
	name: 'André Silva',
	handle: 'andresilvalab',
	github: 'https://github.com/andresilvalab',
	repo: 'https://github.com/andresilvalab/ai-ops-sec',
	linkedin: 'https://www.linkedin.com/in/andre-silva-business-automation/',
	company: { name: 'Wise Pirates', url: 'https://wisepirates.com/', contact: 'https://wisepirates.com/contacts/' },
};

export const SITE = {
	pt: {
		title: 'André Silva Lab',
		tagline: 'Laboratório de IA agêntica, com prova.',
		description:
			'Agentes de IA em produção: como se constroem, operam, avaliam, governam e atacam, testados num stack real. Área em destaque: AI Ops Sec, segurança e observabilidade de agentes.',
		locale: 'pt-PT',
	},
	en: {
		title: 'André Silva Lab',
		tagline: 'An agentic AI lab, with evidence.',
		description:
			'AI agents in production: how they are built, operated, evaluated, governed and attacked, tested on a real stack. Flagship area: AI Ops Sec, agent security and observability.',
		locale: 'en',
	},
} as const;

export const UI = {
	pt: {
		nav_blog: 'Artigos',
		nav_about: 'Sobre',
		nav_scanner: 'Scanner',
		nav_tags: 'Temas',
		nav_areas: 'Áreas',
		areas_title: 'Áreas do laboratório',
		areas_lede: 'Seis frentes do mesmo problema: pôr agentes de IA a trabalhar sem perder o controlo. A primeira é a que este laboratório assina.',
		area_highlight: 'em destaque',
		area_posts: 'artigos',
		area_topics: 'temas',
		in_area: 'Área',
		hero_kicker: 'laboratório de ia agêntica · portugal',
		hero_lines: ['Agentes de IA em produção,', 'construídos, observados', 'e atacados', 'com prova.'],
		skip: 'Saltar para o conteúdo',
		latest: 'Últimos artigos',
		all_posts: 'Todos os artigos',
		read: 'ler',
		min_read: 'min de leitura',
		published: 'publicado',
		updated: 'actualizado',
		verified: 'verificado',
		verified_on: 'verificado a',
		sources: 'fontes',
		sources_title: 'Fontes',
		changelog_title: 'Histórico de alterações',
		accessed: 'consultado a',
		lang_switch: 'Read in English',
		lang_switch_short: 'EN',
		theme: 'Alternar tema',
		search: 'Pesquisar',
		trace: 'trace',
		no_posts: 'O primeiro artigo está em revisão. Subscreve o RSS para o receber.',
		rss: 'RSS',
		tags_title: 'Temas',
		tagged: 'Artigos com o tema',
		in_series: 'Série',
		cite: 'Citar este artigo',
		how_built: 'Como este site é construído',
		how_built_items: [
			'Código e artigos num repositório público. Cada alteração entra por pull request revisto.',
			'Sem trackers, sem cookies, sem scripts de terceiros. HTML estático servido por CDN.',
			'Cada artigo lista as fontes e o que mudou depois de publicado.',
			'Erros corrigem-se em público, no histórico do próprio artigo.',
		],
		not_found: 'Página não encontrada',
		not_found_body: 'Este endereço não existe ou mudou. O índice de artigos está a um clique.',
		back_home: 'Voltar ao início',
		footer_source: 'Código-fonte',
		footer_license: 'Texto CC BY 4.0 · Código MIT',
		footer_security: 'Reportar falha de segurança',
		footer_no_trackers: 'Sem trackers. Sem cookies.',
		og_kicker: 'André Silva Lab · IA agêntica com prova',
	},
	en: {
		nav_blog: 'Articles',
		nav_about: 'About',
		nav_scanner: 'Scanner',
		nav_tags: 'Topics',
		nav_areas: 'Areas',
		areas_title: 'Lab areas',
		areas_lede: 'Six fronts of the same problem: putting AI agents to work without losing control. The first one is the lab\'s signature.',
		area_highlight: 'flagship',
		area_posts: 'articles',
		area_topics: 'topics',
		in_area: 'Area',
		hero_kicker: 'agentic ai lab · portugal',
		hero_lines: ['AI agents in production,', 'built, observed', 'and attacked', 'with evidence.'],
		skip: 'Skip to content',
		latest: 'Latest articles',
		all_posts: 'All articles',
		read: 'read',
		min_read: 'min read',
		published: 'published',
		updated: 'updated',
		verified: 'verified',
		verified_on: 'verified on',
		sources: 'sources',
		sources_title: 'Sources',
		changelog_title: 'Change history',
		accessed: 'accessed',
		lang_switch: 'Ler em português',
		lang_switch_short: 'PT',
		theme: 'Toggle theme',
		search: 'Search',
		trace: 'trace',
		no_posts: 'The first article is under review. Subscribe to the RSS feed to get it.',
		rss: 'RSS',
		tags_title: 'Topics',
		tagged: 'Articles tagged',
		in_series: 'Series',
		cite: 'Cite this article',
		how_built: 'How this site is built',
		how_built_items: [
			'Code and articles live in a public repository. Every change lands through a reviewed pull request.',
			'No trackers, no cookies, no third-party scripts. Static HTML served from a CDN.',
			'Every article lists its sources and what changed after publication.',
			'Mistakes are fixed in public, in the history of the article itself.',
		],
		not_found: 'Page not found',
		not_found_body: 'This address does not exist or has moved. The article index is one click away.',
		back_home: 'Back to home',
		footer_source: 'Source code',
		footer_license: 'Text CC BY 4.0 · Code MIT',
		footer_security: 'Report a security issue',
		footer_no_trackers: 'No trackers. No cookies.',
		og_kicker: 'André Silva Lab · agentic AI with evidence',
	},
} as const;
